# Display a box
print("##########")
print("#        #")
print("#        #")
print("##########")
print("Please enter a character for Beep's eyes!")
character=input()
print("Beep's expression is now as foloows:")
print("##########")
print("#  o  o  #")
print("#        #")
print("##########")
