
print("What is your name?")
name=input()
print("How old are you (in years)?")
age= int (input())
print("How tall are you (in meters)?")
height= int (input())
print("How much do you weigh (in kilograms)?")
weight= int (input())
bmi= float(weight()/height()**2)
print("Name{} you are {} years old and your bmi is {} .")